---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-backup-tool
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-backup-tool
  namespace: grafana-backup-tool
data:
  GRAFANA_URL: "http://34.31.226.46:3000"
  GRAFANA_TOKEN: "TOKEN"
  GRAFANA_ADMIN_ACCOUNT: "admin"
  GRAFANA_ADMIN_PASSWORD: "admin"
  GCS_BUCKET_NAME: "altyn_bucket123"
  GCS_BUCKET_PATH: "grafana-backup-folder"
  GCS_PROJECT_ID: "electric-wave-418217"
  GOOGLE_APPLICATION_CREDENTIALS: "/opt/grafana-backup-tool/application_default_credentials.json"
---
# Run grafana-backup-tool daily and store backups in an S3
# compatible object storage such as minio
apiVersion: batch/v1
kind: CronJob
metadata:
  name: grafana-backup-tool
  namespace: grafana-backup-tool
  labels:
    app: grafana-backup-tool
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    metadata:
      labels:
        app: grafana-backup-tool
    spec:
      template:
        spec:
          restartPolicy: "Never"
          containers:
            - name: grafana-backup-tool
              image: "altyn/grafana-backup-tool:latest"
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: grafana-backup-tool
